app = "vendoc-go"
primary_region = "iad"

[build]

[env]
  PORT = "8080"
  SESSION_TIMEOUT_MINUTES = "30"
  MAX_FILE_SIZE_MB = "10"

[[services]]
  http_checks = []
  internal_port = 8080
  protocol = "tcp"
  
  [[services.ports]]
    port = 80
    handlers = ["http"]
    
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[services.concurrency]
  hard_limit = 25
  soft_limit = 20